auctions/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

from . import views

urlpatterns = [
    path("", views.index, name="index"),
    path("login", views.login_view, name="login"),
    path("logout", views.logout_view, name="logout"),
    path("register", views.register, name="register"),
    path("create", views.create, name="create"),
    path("listing/<int:listing_id>", views.listing, name="listing"),
    path("watchlist", views.watchlist, name="watchlist"),
    path("categories", views.categories, name="categories"),
    path("category/<str:cat>", views.category, name="category"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

commerce/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("auctions.urls"))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

auctions/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.forms import ModelForm

class User(AbstractUser):
    pass

class Bid(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="bid")
    bid_price=models.DecimalField(max_digits=8, decimal_places=2, blank=True)

    def __str__(self):
        return f"{self.user} bidding ${self.bid_price}"

class Auction(models.Model):
    CATEGORIES = [
        ('Clothes', 'Clothes'),
        ('Electronics', 'Devices & Electronics'),
        ('Health', 'Health & Foods'),
        ('Hobbies', 'Hobbies'),
        ('Toys', 'Kids & Toys'),
        ('Sports', 'Sports'),
        ('Tools', 'Tools & Services'),
        ('OTHER', 'None'),
    ]
    title = models.CharField(max_length=100)
    description = models.TextField()
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="owner")
    starting_bid = models.DecimalField(max_digits=8, decimal_places=2)
    bids = models.ManyToManyField(Bid, blank=True, related_name="listing", null=True)
    current_price = models.DecimalField(max_digits=8, decimal_places=2)
    winner = models.ForeignKey(User, related_name="wins", on_delete=models.CASCADE, blank=True, null=True)
    url = models.ImageField(blank=True)
    category = models.CharField(max_length=100, choices=CATEGORIES, default=CATEGORIES[7][0], blank=True)
    closed = models.BooleanField(default=False)

    def __str__(self):
        return f"{self.title} from {self.user}"

class AuctionForm(ModelForm):
    class Meta: 
        model = Auction
        fields = ['title', 'description', 'starting_bid', 'url', 'category']

    def __init__(self, *args, **kwargs):
        super(AuctionForm, self).__init__(*args, **kwargs)
        for fname, f in self.fields.items():
            f.widget.attrs['class'] = 'form-control'

class WatchList(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="watched")
    listing = models.ForeignKey(Auction, on_delete=models.CASCADE, related_name="watcher")

    def __str__(self):
        return f"{self.user} watching {self.listing}"

class BidForm(ModelForm):
    class Meta: 
        model = Bid
        fields = ['bid_price']

    def __init__(self, *args, **kwargs):
        super(BidForm, self).__init__(*args, **kwargs)
        for fname, f in self.fields.items():
            f.widget.attrs['class'] = 'form-control'

class Comment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="comments")
    text = models.TextField()
    listing = models.ForeignKey(Auction, on_delete=models.CASCADE, related_name="comments", null=True)
    datetime = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return f"{self.user} commented {self.text}"

class CommentForm(ModelForm):
    class Meta: 
        model = Comment
        fields = ['text']

    def __init__(self, *args, **kwargs):
        super(CommentForm, self).__init__(*args, **kwargs)
        for fname, f in self.fields.items():
            f.widget.attrs['class'] = 'form-control'

auctions/views.py
from django.contrib.auth import authenticate, login, logout
from django.db import IntegrityError
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
from django.contrib.auth.decorators import login_required

from .models import User, Auction, AuctionForm, WatchList, Bid, BidForm, Comment, CommentForm

def index(request):
    auctions = Auction.objects.all()
    liveauctions = auctions.filter(closed=False)
    deadauctions = auctions.filter(closed=True)
    return render(request, "auctions/index.html", {
        "liveauctions": liveauctions,
        "deadauctions": deadauctions,
    })

def login_view(request):
    if request.method == "POST":

        # Attempt to sign user in
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(request, username=username, password=password)

        # Check if authentication successful
        if user is not None:
            login(request, user)
            return HttpResponseRedirect(reverse("index"))
        else:
            return render(request, "auctions/login.html", {
                "message": "Invalid username and/or password."
            })
    else:
        return render(request, "auctions/login.html")


def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse("index"))


def register(request):
    if request.method == "POST":
        username = request.POST["username"]
        email = request.POST["email"]

        # Ensure password matches confirmation
        password = request.POST["password"]
        confirmation = request.POST["confirmation"]
        if password != confirmation:
            return render(request, "auctions/register.html", {
                "message": "Passwords must match."
            })

        # Attempt to create new user
        try:
            user = User.objects.create_user(username, email, password)
            user.save()
        except IntegrityError:
            return render(request, "auctions/register.html", {
                "message": "Username already taken."
            })
        login(request, user)
        return HttpResponseRedirect(reverse("index"))
    else:
        return render(request, "auctions/register.html")

@login_required(login_url='/login')
def create(request):
    if request.method == "POST":
        # Access username
        user = User.objects.get(username=request.user)

        # Take in data submitted and save as form
        form = AuctionForm(request.POST, request.FILES)

        # Check if form data is valid
        if form.is_valid(): 
            auction = form.save(commit=False)
            auction.user = user
            auction.winner = user
            auction.current_price = auction.starting_bid
            auction.save()

        return HttpResponseRedirect(reverse("index"))
    else:
        return render(request, "auctions/create.html", {
            "form": AuctionForm()
        })

@login_required(login_url='/login')
def listing(request, listing_id):
    # Access username
    user = User.objects.get(username=request.user)
    # Access listing
    listing = Auction.objects.get(pk = listing_id)
    # Access comments
    try:
        comments = Comment.objects.filter(listing = listing_id).all().order_by('datetime')
    except Comment.DoesNotExist:
        comments = None

    # Set wachlist text
    if user.watched.filter(listing=listing): 
        watchlist_text = "Stop Watching"
    else:
        watchlist_text = "Watchlist"

    if request.method == "POST":
        # If owner closes listing
        if 'close' in request.POST:
            listing.closed = True
            listing.save()

            return render(request, "auctions/listing.html", {
                "listing": listing,
                "comments": comments,
                "commentform": CommentForm()
            })

        # If comment is added
        if 'commentpost' in request.POST: 
            form = CommentForm(request.POST)
            if form.is_valid():
                comment = form.save(commit=False)
                comment.user = user
                comment.listing = listing
                comment.save()

        # Else if watchlist button is clicked
        elif 'watchlist' in request.POST:
            if user.watched.filter(listing=listing):
                user.watched.filter(listing = listing).delete()
                watchlist_text = "Watchlist"
            else: 
                watch = WatchList()
                watch.user = user
                watch.listing = listing
                watch.save()
                watchlist_text = "Stop Watching"

        # Else if a bid is submitted
        elif 'bid' in request.POST:
            # Take in data submitted 
            form = BidForm(request.POST)

            # Check if form data is valid
            if form.is_valid(): 
                bid = form.save(commit=False)

                if bid.bid_price == None or bid.bid_price < listing.current_price:
                    return render(request, "auctions/listing.html", {
                        "listing": listing,
                        "watchlist_text": watchlist_text,
                        "bidform": BidForm(),
                        "message": "Error: Invalid bid price!",
                        "comments": comments,
                        "commentform": CommentForm()
                    })
                else:
                    bid.user = user
                    bid.save()
                    listing.current_price = bid.bid_price
                    listing.winner = user
                    listing.save()

        return render(request, "auctions/listing.html", {
            "listing": listing,
            "watchlist_text": watchlist_text,
            "bidform": BidForm(),
            "comments": comments, 
            "commentform": CommentForm()
        })

    # Else, if owner is checking in
    if user == listing.user and listing.closed == False:
        return render(request, "auctions/listing.html", {
            "listing": listing,
            "owner": True,
            "comments": comments,
            "commentform": CommentForm()
        })

    # Else, if winner is checking in on closed listing
    elif user == listing.winner and listing.closed:
        return render(request, "auctions/listing.html", {
            "listing": listing,
            "winner": True, 
            "comments": comments,
            "commentform": CommentForm()
        })


    # Otherwise, default load
    return render(request, "auctions/listing.html", {
        "listing": listing,
        "watchlist_text":watchlist_text,
        "bidform": BidForm(),
        "comments": comments,
        "commentform": CommentForm()
    })

@login_required(login_url='/login')
def watchlist(request):
    # Access username
    user = User.objects.get(username=request.user)
    # Get watchlisted listings
    watchauctions = user.watched.all()
    liveauctions = watchauctions.filter(listing__closed = False)
    deadauctions = watchauctions.filter(listing__closed = True)

    return render(request, "auctions/watchlist.html", {
        "liveauctions": liveauctions,
        "deadauctions": deadauctions,
    })

def categories(request):
    categories = Auction.category.field.choices
    return render(request, "auctions/categories.html", {
        "categories": categories,
    })

def category(request, cat):
    # Access listing
    everylisting = Auction.objects.all()
    listings = everylisting.filter(category = cat)
    livelistings = listings.filter(closed = False)
    deadlistings = listings.filter(closed = True)
    return render(request, "auctions/category.html", {
        "category": cat,
        "deadlistings": deadlistings,
        "livelistings": livelistings,
    })

auctions/templates/auctions/categories.html
{% extends "auctions/layout.html" %}

{% block body %}
    <h2>Categories</h2>
    <ul>
        {% for cat in categories %}
            <li>
                <a href="{% url 'category' cat.0 %}">{{ cat.1 }}</a>
            </li>
        {% endfor %}
        </ul>
{% endblock %}

auctions/templates/auctions/category.html
{% extends "auctions/layout.html" %}

{% block body %}
    <h2>{{ category }}</h2>
    <div class="listings">
        {% for auction in livelistings %}
            <div class="listing">
                <h3><a href="{% url 'listing' auction.id %}">{{ auction.title }}</a></h3>
                <p class="index-price">Current price: $ {{ auction.current_price }}</p>
                {% if auction.url.url %}
                <img src="{{ auction.url.url }}" alt="Image" class="index-image">
                {% endif %}
                <p class="index-description">{{ auction.description }}</p>
            </div>
        {% endfor %}
    </div>
    {% if deadlistings %}
        <h3>Closed</h3>
        <div class="listings">
            {% for auction in deadlistings %}
                <div class="listing">
                    <h3><a href="{% url 'listing' auction.id %}">{{ auction.title }}</a></h3>
                    <p class="index-price">Current price: $ {{ auction.current_price }}</p>
                    {% if auction.url.url %}
                    <img src="{{ auction.url.url }}" alt="Image" class="index-image">
                    {% endif %}
                    <p class="index-description">{{ auction.description }}</p>
                </div>
            {% endfor %}
        </div>
    {% endif %}
{% endblock %}

auctions/templates/auctions/create.html
{% extends "auctions/layout.html" %}
{% block title %} Create Page {% endblock %}
{% block body %}
    <h2>Create New Listing</h2>
    <form action="{% url 'create' %}" enctype="multipart/form-data" method="post">
        {% csrf_token %}
        <div class="form-group">
            {{ form.title.label_tag }}
            {{ form.title }}
        </div>
        <div class="form-group">
            {{ form.description.label_tag }}
            {{ form.description }}
        </div>
        <div class="form-group">
            <span style="position: absolute; margin-left: 10px; margin-top: 38px;">$</span>
            {{ form.starting_bid.label_tag }}
            {{ form.starting_bid }}
        </div>
        <div class="form-group">
            {{ form.url.label_tag }}
            {{ form.url }}
        </div>
        <div class="form-group">
            {{ form.category.label_tag }}
            {{ form.category }}
        </div>
        <input class="btn btn-primary" type="submit" value="Submit">
    </form>
{% endblock %}

auctions/templates/auctions/index.html
{% extends "auctions/layout.html" %}

{% block body %}
    <h2><a id="active">Active Listings</a></h2>
    <div class="listings">
        {% for auction in liveauctions %}
            <div class="listing">
                <h3><a href="{% url 'listing' auction.id %}">{{ auction.title }}</a></h3>
                <p class="index-price">Current price: $ {{ auction.current_price }}</p>
                {% if auction.url.url %}
                <img src="{{ auction.url.url }}" alt="Image" class="index-image">
                {% endif %}
                <p class="index-description">{{ auction.description }}</p>
            </div>
        {% endfor %}
    </div>

    <br><br>
    <h2><a id="inactive">Inactive Listings</a></h2>
    <div class="listings">
        {% for auction in deadauctions %}
            <div class="listing">
                <h3><a href="{% url 'listing' auction.id %}">{{ auction.title }}</a></h3>
                <p class="index-price">Current price: $ {{ auction.current_price }}</p>
                {% if auction.url.url %}
                <img src="{{ auction.url.url }}" alt="Image" class="index-image">
                {% endif %}
                <p class="index-description">{{ auction.description }}</p>
            </div>
        {% endfor %}
    </div>
{% endblock %}

auctions/templates/auctions/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <title>{% block title %}Auctions{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'auctions/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <h1>Auctions</h1>
        <div>
            {% if user.is_authenticated %}
                Signed in as <strong>{{ user.username }}</strong>.
            {% else %}
                Not signed in.
            {% endif %}
        </div>
        <ul class="nav">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'index' %}#active">Active Listings</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'index' %}#inactive">Inactive Listings</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'categories' %}">Categories</a>
            </li>
            {% if user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'create' %}">Create Listing</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'watchlist' %}">Watchlist</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'logout' %}">Log Out</a>
                </li>
            {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'login' %}">Log In</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'register' %}">Register</a>
                </li>
            {% endif %}
        </ul>
        <hr>
        {% block body %}
        {% endblock %}
    </body>
</html>

auctions/templates/auctions/listing.html
{% extends "auctions/layout.html" %}
{% block title %} Auction {% endblock %}

{% block body %}
    <h2>{{ listing.title }}</h2>
    {% if listing.url.url %}
    <img src="{{ listing.url.url }}" alt="Image" class="listing-image">
    {% endif %}
    <p><span class="infotext">Listed by:</span> {{ listing.user }}</p>
    <p><span class="infotext">Description:</span> {{ listing.description }}</p>
    <p><span class="infotext">Current price is:</span> ${{ listing.current_price }} <span class="infotext"> from </span> {{ listing.winner }} </p>
    <p><span class="infotext">Category:</span> {{ listing.get_category_display }}</p>

    {% if listing.closed %}
        {% if winner %}
            <div class="alert alert-success center-alert">Congratulations! You won the {{ listing.title }} for {{ listing.current_price }}!</div>
        {% endif %}
        <div class="alert alert-danger center-alert">This listing is closed!</div>


    {% elif owner %}
        <form action="{% url 'listing' listing.id %}" method="post">
            {% csrf_token %}
            <input class="btn btn-primary center-button" type="submit" name="close" value="Close listing">
        </form>

    {% else %}
        {% if message %}
            <div class="alert alert-danger center-alert">{{ message }}</div>
        {% endif %}

        <form action="{% url 'listing' listing.id %}" method="post">
            {% csrf_token %}
            <div class="form-group bidform">
                {{ bidform.bid_price.label_tag }}
                {{ bidform.bid_price }}
            </div>
            <div class="buttons">
              <input class="btn btn-primary center-button" type="submit" name="bid" value="Make a bid">
              <input class="btn btn-secondary" type="submit" name="watchlist" value="{{ watchlist_text }}">
            </div>
        </form>
    {% endif %}

    <div class="comments">
        <h3>Comments</h3>

        <div class="read-comments">
            {% for comment in comments %}
              <div class="comment">
                  <h4>{{ comment.user }}</h4>
                  <p>{{ comment.text }}</p>
                  <p class="datetime">{{ comment.datetime }}</p>
              </div>
            {% endfor %}
        </div>

        <form action="{% url 'listing' listing.id %}" method="post" class="commenting">
            {% csrf_token %}
            <div class="form-group commentarea">
                <label for="id_text">Add comment: </label>
                {{ commentform.text }}
            </div>
            <input class="btn btn-info" type="submit" name="commentpost" value="Comment">
        </form>
    </div>
{% endblock %}

auctions/templates/auctions/login.html
{% extends "auctions/layout.html" %}

{% block body %}

    <h2>Login</h2>

    {% if message %}
        <div>{{ message }}</div>
    {% endif %}

    <form action="{% url 'login' %}" method="post">
        {% csrf_token %}
        <div class="form-group">
            <input autofocus class="form-control" type="text" name="username" placeholder="Username">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="password" placeholder="Password">
        </div>
        <input class="btn btn-primary" type="submit" value="Login">
    </form>

    Don't have an account? <a href="{% url 'register' %}">Register here.</a>

{% endblock %}

auctions/templates/auctions/register.html
{% extends "auctions/layout.html" %}

{% block body %}

    <h2>Register</h2>

    {% if message %}
        <div>{{ message }}</div>
    {% endif %}

    <form action="{% url 'register' %}" method="post">
        {% csrf_token %}
        <div class="form-group">
            <input class="form-control" autofocus type="text" name="username" placeholder="Username">
        </div>
        <div class="form-group">
            <input class="form-control" type="email" name="email" placeholder="Email Address">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="password" placeholder="Password">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="confirmation" placeholder="Confirm Password">
        </div>
        <input class="btn btn-primary" type="submit" value="Register">
    </form>

    Already have an account? <a href="{% url 'login' %}">Log In here.</a>

{% endblock %}

auctions/templates/auctions/watchlist.html
{% extends "auctions/layout.html" %}

{% block body %}
    <h2>Watchlist</h2>
    <div class="listings">
        {% for auction in liveauctions %}
            <div class="listing">
                <h3><a href="{% url 'listing' auction.listing.id %}">{{ auction.listing.title }}</a></h3>
                <p class="index-price">Current price: $ {{ auction.listing.current_price }}</p>
                {% if auction.listing.url.url %}
                <img src="{{ auction.listing.url.url }}" alt="Image" class="index-image">
                {% endif %}
                <p>{{ auction.listing.description }}</p>
            </div>
        {% endfor %}
    </div>
    {% if deadauctions %}
        <h3>Closed</h3>
        <div class="listings">
            {% for auction in deadauctions %}
                <div class="listing">
                    <h3><a href="{% url 'listing' auction.listing.id %}">{{ auction.listing.title }}</a></h3>
                    <p class="index-price">Current price: $ {{ auction.listing.current_price }}</p>
                    {% if auction.listing.url.url %}
                    <img src="{{ auction.listing.url.url }}" alt="Image" class="index-image">
                    {% endif %}
                    <p>{{ auction.listing.description }}</p>
                </div>
            {% endfor %}
        </div>
    {% endif %}
{% endblock %}